// Passphrase wordlist — short, common English words, easy to read out loud.
// 4 words + 2-digit number ≈ log2(320^4 × 90) ≈ 40 bits of entropy; combined with
// PBKDF2 at 310k iterations to resist offline brute-force of the SDP blob.
export const WORDS = [
  'acid', 'acorn', 'actor', 'adobe', 'alarm', 'album', 'alien', 'alley', 'aloe', 'amber',
  'anchor', 'angle', 'ankle', 'apple', 'apron', 'arch', 'arena', 'argon', 'arrow', 'ash',
  'atlas', 'atom', 'attic', 'audio', 'avid', 'axis', 'bacon', 'badge', 'bagel', 'baker',
  'bamboo', 'banjo', 'barge', 'barn', 'basil', 'bass', 'baton', 'beach', 'bead', 'beak',
  'bean', 'bear', 'beast', 'bell', 'belt', 'bench', 'berry', 'bike', 'birch', 'bird',
  'bison', 'blade', 'blaze', 'blimp', 'bloom', 'blush', 'board', 'boat', 'bolt', 'bone',
  'bonus', 'book', 'boot', 'booth', 'brave', 'bread', 'brick', 'bride', 'brim', 'brook',
  'broom', 'brush', 'bud', 'budge', 'bulb', 'bunny', 'bus', 'cabin', 'cable', 'cactus',
  'cadet', 'cake', 'camel', 'camp', 'canal', 'candy', 'canoe', 'cape', 'cargo', 'carol',
  'carve', 'cave', 'cedar', 'cello', 'chalk', 'charm', 'chef', 'chess', 'chest', 'chief',
  'chill', 'chime', 'chip', 'churn', 'cider', 'cinch', 'city', 'civic', 'clay', 'clean',
  'cliff', 'climb', 'cloak', 'clock', 'cloud', 'clove', 'coach', 'coast', 'cobra', 'cocoa',
  'coil', 'coin', 'colt', 'comet', 'coral', 'cork', 'cove', 'crab', 'craft', 'crane',
  'crate', 'creek', 'crepe', 'crib', 'crown', 'cub', 'cube', 'curve', 'cycle', 'daisy',
  'dandy', 'dart', 'dawn', 'deck', 'deer', 'delta', 'denim', 'depot', 'derby', 'desk',
  'dice', 'dime', 'diner', 'dingo', 'dock', 'dome', 'donor', 'donut', 'dose', 'dove',
  'dozen', 'drake', 'dress', 'drift', 'drum', 'dry', 'duck', 'dune', 'dusk', 'eagle',
  'earth', 'easel', 'echo', 'eel', 'elbow', 'elder', 'elk', 'elm', 'ember', 'emu',
  'epic', 'essay', 'evoke', 'fable', 'facet', 'fang', 'fawn', 'feast', 'fence', 'fern',
  'ferry', 'fever', 'fife', 'fig', 'film', 'finch', 'fjord', 'flag', 'flame', 'flare',
  'flask', 'fleet', 'flint', 'flock', 'flora', 'flute', 'foam', 'fog', 'font', 'forge',
  'fox', 'frame', 'freon', 'frost', 'fruit', 'gala', 'gauge', 'gecko', 'gem', 'genie',
  'gift', 'gig', 'ginger', 'glade', 'glass', 'glide', 'globe', 'glow', 'gnome', 'goat',
  'gong', 'goose', 'gorge', 'gourd', 'grain', 'grape', 'grasp', 'grass', 'grill', 'grove',
  'guide', 'gulf', 'gull', 'gust', 'habit', 'halo', 'harbor', 'harp', 'hatch', 'haven',
  'hawk', 'hazel', 'heron', 'hill', 'hive', 'holly', 'honey', 'hood', 'horn', 'horse',
  'hotel', 'house', 'husk', 'hut', 'icon', 'igloo', 'inlet', 'iris', 'irony', 'ivory',
  'ivy', 'jade', 'jazz', 'jeep', 'jelly', 'jewel', 'jolt', 'judge', 'juice', 'jumbo',
  'jungle', 'juror', 'kayak', 'kazoo', 'keel', 'keep', 'kelp', 'kettle', 'kilt', 'kite',
  'kiwi', 'knack', 'knee', 'knoll', 'koala', 'lagoon', 'lake', 'lamb', 'lamp', 'lance',
  'lapel', 'larch', 'lark', 'latch', 'lava', 'lawn', 'ledge', 'lemon', 'lentil', 'level',
  'lilac', 'lily', 'lime', 'linen', 'lion', 'llama', 'lodge', 'loft', 'logo', 'lotus',
]
